# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4fd0955abb3cd000347715829b53976098e3edc2b39416f94090d8378b6c991b3119009bb0c184f9d6e23c3710d4f23a72ee7134dae1aa68865696f628f995

test:
  secret_key_base: 0f9f161d8a653e5fcc18db9bd73b507d8a178c62ea06075866b43d9157081a8658696856ae0c77335b3e2e66ad39e0d30ec10253e7f92b529aed0dd248801caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
